name = "battery"
main = "worker.js"
compatibility_date = "2024-01-01" # Используйте дату в прошлом

# Привязка KV (замените ID на свой)
[[kv_namespaces]]
binding = "BATTERY_KV"
id = "f60c5efc4da34e3d8e341abccd5b2ff8"
